"""add feature bin releases table

Revision ID: 1567a07a55b6
Revises: dc5476037a42
Create Date: 2026-09-10 18:37:27.323609

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1567a07a55b6"
down_revision: Union[str, None] = "dc5476037a42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_bin_releases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("added_date", sa.String(), nullable=True),
        sa.Column("artist", sa.String(), nullable=False),
        sa.Column("album", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("released_year", sa.String(), nullable=True),
        sa.Column("dot", sa.String(), nullable=True),
        sa.Column("media", sa.String(), nullable=True),
        sa.Column("reviewer", sa.String(), nullable=True),
        sa.Column("sheet_status", sa.String(), nullable=True),
        sa.Column("media_url", sa.String(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feature_bin_releases_artist"),
        "feature_bin_releases",
        ["artist"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feature_bin_releases_id"), "feature_bin_releases", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feature_bin_releases_id"), table_name="feature_bin_releases")
    op.drop_index(op.f("ix_feature_bin_releases_artist"), table_name="feature_bin_releases")
    op.drop_table("feature_bin_releases")
    # ### end Alembic commands ###
