"""add kalx live appearances table

Revision ID: a1f3c9d0e7b2
Revises: 07bbdf2b0518
Create Date: 2026-09-14 21:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a1f3c9d0e7b2"
down_revision: Union[str, None] = "07bbdf2b0518"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kalx_live_appearances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("band_name", sa.String(), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_kalx_live_appearances_band_name"),
        "kalx_live_appearances",
        ["band_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kalx_live_appearances_id"), "kalx_live_appearances", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kalx_live_appearances_id"), table_name="kalx_live_appearances")
    op.drop_index(
        op.f("ix_kalx_live_appearances_band_name"), table_name="kalx_live_appearances"
    )
    op.drop_table("kalx_live_appearances")
    # ### end Alembic commands ###
