"""initial schema

Revision ID: dc5476037a42
Revises:
Create Date: 2026-09-01 15:49:12.900071

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "dc5476037a42"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("actor_email", sa.String(), nullable=True),
        sa.Column("actor_role", sa.String(), nullable=True),
        sa.Column("entity_type", sa.String(), nullable=True),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_log_event_type"), "audit_log", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_audit_log_id"), "audit_log", ["id"], unique=False)
    op.create_index(
        op.f("ix_audit_log_occurred_at"), "audit_log", ["occurred_at"], unique=False
    )
    op.create_table(
        "external_api_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_external_api_cache_expires_at"),
        "external_api_cache",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_api_cache_id"), "external_api_cache", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_external_api_cache_url"), "external_api_cache", ["url"], unique=True
    )
    op.create_table(
        "impersonation_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("real_email", sa.String(), nullable=False),
        sa.Column("impersonated_email", sa.String(), nullable=True),
        sa.Column("impersonate_dj_network", sa.Boolean(), nullable=False),
        sa.Column("impersonate_station_office_network", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_impersonation_sessions_id"), "impersonation_sessions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_impersonation_sessions_real_email"),
        "impersonation_sessions",
        ["real_email"],
        unique=False,
    )
    op.create_table(
        "job_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("ran_at", sa.DateTime(), nullable=False),
        sa.Column("trigger", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_log_id"), "job_log", ["id"], unique=False)
    op.create_index(op.f("ix_job_log_job_id"), "job_log", ["job_id"], unique=False)
    op.create_table(
        "promoters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("pass_call_instructions", sa.Text(), nullable=True),
        sa.Column(
            "requires_phone_number", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "requires_email_address", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "staff_guest_requires_name",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_promoters_id"), "promoters", ["id"], unique=False)
    op.create_index(op.f("ix_promoters_name"), "promoters", ["name"], unique=True)
    op.create_table(
        "specialty_shows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_specialty_shows_id"), "specialty_shows", ["id"], unique=False)
    op.create_index(
        op.f("ix_specialty_shows_name"), "specialty_shows", ["name"], unique=True
    )
    op.create_table(
        "staff",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("spinitron_ids", sa.JSON(), nullable=True),
        sa.Column("dj_name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_staff_email"), "staff", ["email"], unique=True)
    op.create_index(op.f("ix_staff_id"), "staff", ["id"], unique=False)
    op.create_table(
        "notification_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("staff_id", sa.Integer(), nullable=False),
        sa.Column("email_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("staff_id", name="uq_notification_preferences_staff_id"),
    )
    op.create_index(
        op.f("ix_notification_preferences_id"),
        "notification_preferences",
        ["id"],
        unique=False,
    )
    op.create_table(
        "promoter_contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("promoter_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["promoter_id"],
            ["promoters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_promoter_contacts_id"), "promoter_contacts", ["id"], unique=False
    )
    op.create_table(
        "promoter_owners",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("promoter_id", sa.Integer(), nullable=False),
        sa.Column("staff_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["promoter_id"],
            ["promoters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_promoter_owners_id"), "promoter_owners", ["id"], unique=False)
    op.create_table(
        "specialty_show_djs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("specialty_show_id", sa.Integer(), nullable=False),
        sa.Column("dj_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["specialty_show_id"],
            ["specialty_shows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_specialty_show_djs_dj_name"),
        "specialty_show_djs",
        ["dj_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_specialty_show_djs_id"), "specialty_show_djs", ["id"], unique=False
    )
    op.create_table(
        "specialty_show_owners",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("specialty_show_id", sa.Integer(), nullable=False),
        sa.Column("staff_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["specialty_show_id"],
            ["specialty_shows.id"],
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_specialty_show_owners_id"), "specialty_show_owners", ["id"], unique=False
    )
    op.create_table(
        "staff_departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("staff_id", sa.Integer(), nullable=False),
        sa.Column("department", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("staff_id", "department", name="uq_staff_department"),
    )
    op.create_index(
        op.f("ix_staff_departments_id"), "staff_departments", ["id"], unique=False
    )
    op.create_table(
        "staff_statuses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("staff_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("staff_id", "status", name="uq_staff_status"),
    )
    op.create_index(op.f("ix_staff_statuses_id"), "staff_statuses", ["id"], unique=False)
    op.create_table(
        "venues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("pass_call_instructions", sa.Text(), nullable=True),
        sa.Column("win_frequency_days", sa.Integer(), nullable=True),
        sa.Column("default_wheelchair_accessible", sa.Boolean(), nullable=True),
        sa.Column("default_age_restriction", sa.String(), nullable=True),
        sa.Column("default_num_pass_pairs", sa.Integer(), nullable=True),
        sa.Column("logo_filename", sa.String(), nullable=True),
        sa.Column(
            "requires_phone_number", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "requires_email_address", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "staff_guest_requires_name",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "default_lottery_enabled", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "default_lottery_window_hours",
            sa.Integer(),
            server_default=sa.text("(24)"),
            nullable=False,
        ),
        sa.Column("default_dj_preassign_prohibition_days", sa.Integer(), nullable=True),
        sa.Column("default_close_hours_before_show", sa.Integer(), nullable=True),
        sa.Column("promoter_id", sa.Integer(), nullable=True),
        sa.Column(
            "shows_have_external_promoter",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["promoter_id"],
            ["promoters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_venues_id"), "venues", ["id"], unique=False)
    op.create_index(op.f("ix_venues_name"), "venues", ["name"], unique=True)
    op.create_table(
        "shows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_name", sa.String(), nullable=False),
        sa.Column("genre", sa.JSON(), nullable=True),
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("promoter_id", sa.Integer(), nullable=True),
        sa.Column("show_date", sa.Date(), nullable=False),
        sa.Column("show_time", sa.Time(), nullable=True),
        sa.Column("show_start_date", sa.Date(), nullable=True),
        sa.Column("on_air_description", sa.String(), nullable=True),
        sa.Column("caller_special_instructions", sa.String(), nullable=True),
        sa.Column("age_restriction", sa.String(), nullable=False),
        sa.Column("wheelchair_accessible", sa.Boolean(), nullable=False),
        sa.Column("num_pass_pairs", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("planned_close_date", sa.Date(), nullable=True),
        sa.Column("planned_close_time", sa.Time(), nullable=True),
        sa.Column("auto_close", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("co_announce", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "lottery_enabled", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "lottery_window_hours",
            sa.Integer(),
            server_default=sa.text("(24)"),
            nullable=False,
        ),
        sa.Column("dj_preassign_prohibition_days", sa.Integer(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["promoter_id"],
            ["promoters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shows_id"), "shows", ["id"], unique=False)
    op.create_table(
        "venue_contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_venue_contacts_id"), "venue_contacts", ["id"], unique=False)
    op.create_table(
        "venue_owners",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("staff_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_venue_owners_id"), "venue_owners", ["id"], unique=False)
    op.create_table(
        "lottery_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("show_id", sa.Integer(), nullable=False),
        sa.Column("entry_type", sa.String(), nullable=False),
        sa.Column("staff_id", sa.Integer(), nullable=True),
        sa.Column("dj_name", sa.String(), nullable=True),
        sa.Column("specialty_show_id", sa.Integer(), nullable=True),
        sa.Column("assignment_date", sa.Date(), nullable=True),
        sa.Column("has_guest", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("guest_name", sa.String(), nullable=True),
        sa.Column(
            "only_attend_with_guest", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("status", sa.String(), server_default="pending", nullable=False),
        sa.Column("entered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["show_id"],
            ["shows.id"],
        ),
        sa.ForeignKeyConstraint(
            ["specialty_show_id"],
            ["specialty_shows.id"],
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lottery_entries_id"), "lottery_entries", ["id"], unique=False)
    op.create_index(
        op.f("ix_lottery_entries_show_id"), "lottery_entries", ["show_id"], unique=False
    )
    op.create_index(
        op.f("ix_lottery_entries_staff_id"), "lottery_entries", ["staff_id"], unique=False
    )
    op.create_table(
        "passes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("show_id", sa.Integer(), nullable=False),
        sa.Column("pass_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("given_away_by_dj", sa.String(), nullable=True),
        sa.Column("given_away_at", sa.DateTime(), nullable=True),
        sa.Column("staff_id", sa.Integer(), nullable=True),
        sa.Column("claimed_at", sa.DateTime(), nullable=True),
        sa.Column("preassigned_dj", sa.String(), nullable=True),
        sa.Column("preassigned_date", sa.Date(), nullable=True),
        sa.Column("preassigned_by_staff_id", sa.Integer(), nullable=True),
        sa.Column("preassigned_specialty_show_id", sa.Integer(), nullable=True),
        sa.Column("has_guest", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("guest_name", sa.String(), nullable=True),
        sa.Column(
            "only_attend_with_guest", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("guest_of_pass_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["guest_of_pass_id"],
            ["passes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["preassigned_by_staff_id"],
            ["staff.id"],
        ),
        sa.ForeignKeyConstraint(
            ["preassigned_specialty_show_id"],
            ["specialty_shows.id"],
        ),
        sa.ForeignKeyConstraint(
            ["show_id"],
            ["shows.id"],
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_passes_id"), "passes", ["id"], unique=False)
    op.create_table(
        "show_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("show_id", sa.Integer(), nullable=False),
        sa.Column("dj_name", sa.String(), nullable=False),
        sa.Column("attempted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["show_id"],
            ["shows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_show_attempts_id"), "show_attempts", ["id"], unique=False)
    op.create_table(
        "show_bands",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("show_id", sa.Integer(), nullable=False),
        sa.Column("musicbrainz_id", sa.String(), nullable=False),
        sa.Column("band_name", sa.String(), nullable=False),
        sa.Column("start_pos", sa.Integer(), nullable=False),
        sa.Column("end_pos", sa.Integer(), nullable=False),
        sa.Column("artist_type", sa.String(), nullable=True),
        sa.Column("artist_country", sa.String(), nullable=True),
        sa.Column("artist_disambiguation", sa.String(), nullable=True),
        sa.Column("artist_tags", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["show_id"],
            ["shows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_show_bands_id"), "show_bands", ["id"], unique=False)
    op.create_index(op.f("ix_show_bands_show_id"), "show_bands", ["show_id"], unique=False)
    op.create_table(
        "on_air_winners",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pass_id", sa.Integer(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("show_id", sa.Integer(), nullable=False),
        sa.Column("recipient_name", sa.String(), nullable=False),
        sa.Column("recipient_phone", sa.String(), nullable=False),
        sa.Column("recipient_email", sa.String(), nullable=True),
        sa.Column("given_away_by_dj", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pass_id"],
            ["passes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["show_id"],
            ["shows.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pass_id"),
    )
    op.create_index(op.f("ix_on_air_winners_id"), "on_air_winners", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_on_air_winners_id"), table_name="on_air_winners")
    op.drop_table("on_air_winners")
    op.drop_index(op.f("ix_show_bands_show_id"), table_name="show_bands")
    op.drop_index(op.f("ix_show_bands_id"), table_name="show_bands")
    op.drop_table("show_bands")
    op.drop_index(op.f("ix_show_attempts_id"), table_name="show_attempts")
    op.drop_table("show_attempts")
    op.drop_index(op.f("ix_passes_id"), table_name="passes")
    op.drop_table("passes")
    op.drop_index(op.f("ix_lottery_entries_staff_id"), table_name="lottery_entries")
    op.drop_index(op.f("ix_lottery_entries_show_id"), table_name="lottery_entries")
    op.drop_index(op.f("ix_lottery_entries_id"), table_name="lottery_entries")
    op.drop_table("lottery_entries")
    op.drop_index(op.f("ix_venue_owners_id"), table_name="venue_owners")
    op.drop_table("venue_owners")
    op.drop_index(op.f("ix_venue_contacts_id"), table_name="venue_contacts")
    op.drop_table("venue_contacts")
    op.drop_index(op.f("ix_shows_id"), table_name="shows")
    op.drop_table("shows")
    op.drop_index(op.f("ix_venues_name"), table_name="venues")
    op.drop_index(op.f("ix_venues_id"), table_name="venues")
    op.drop_table("venues")
    op.drop_index(op.f("ix_staff_statuses_id"), table_name="staff_statuses")
    op.drop_table("staff_statuses")
    op.drop_index(op.f("ix_staff_departments_id"), table_name="staff_departments")
    op.drop_table("staff_departments")
    op.drop_index(op.f("ix_specialty_show_owners_id"), table_name="specialty_show_owners")
    op.drop_table("specialty_show_owners")
    op.drop_index(op.f("ix_specialty_show_djs_id"), table_name="specialty_show_djs")
    op.drop_index(op.f("ix_specialty_show_djs_dj_name"), table_name="specialty_show_djs")
    op.drop_table("specialty_show_djs")
    op.drop_index(op.f("ix_promoter_owners_id"), table_name="promoter_owners")
    op.drop_table("promoter_owners")
    op.drop_index(op.f("ix_promoter_contacts_id"), table_name="promoter_contacts")
    op.drop_table("promoter_contacts")
    op.drop_index(
        op.f("ix_notification_preferences_id"), table_name="notification_preferences"
    )
    op.drop_table("notification_preferences")
    op.drop_index(op.f("ix_staff_id"), table_name="staff")
    op.drop_index(op.f("ix_staff_email"), table_name="staff")
    op.drop_table("staff")
    op.drop_index(op.f("ix_specialty_shows_name"), table_name="specialty_shows")
    op.drop_index(op.f("ix_specialty_shows_id"), table_name="specialty_shows")
    op.drop_table("specialty_shows")
    op.drop_index(op.f("ix_promoters_name"), table_name="promoters")
    op.drop_index(op.f("ix_promoters_id"), table_name="promoters")
    op.drop_table("promoters")
    op.drop_index(op.f("ix_job_log_job_id"), table_name="job_log")
    op.drop_index(op.f("ix_job_log_id"), table_name="job_log")
    op.drop_table("job_log")
    op.drop_index(
        op.f("ix_impersonation_sessions_real_email"), table_name="impersonation_sessions"
    )
    op.drop_index(op.f("ix_impersonation_sessions_id"), table_name="impersonation_sessions")
    op.drop_table("impersonation_sessions")
    op.drop_index(op.f("ix_external_api_cache_url"), table_name="external_api_cache")
    op.drop_index(op.f("ix_external_api_cache_id"), table_name="external_api_cache")
    op.drop_index(op.f("ix_external_api_cache_expires_at"), table_name="external_api_cache")
    op.drop_table("external_api_cache")
    op.drop_index(op.f("ix_audit_log_occurred_at"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_event_type"), table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
